baseurl = "https://tsukaharan.github.io/"
languageCode = "ja"
title = "masalog"
canonifyurls = true
theme = "beautifulhugo"


[Params]
  logo = "img/avatar-icon.png"
  subtitle = "ゆるふわBizDeverの備忘録ブログ"

[Author]
  name = "masaru tsukahara"
  email = "tsukaharama@gmail.com"
  facebook = "tsukaharam"
  github = "tsukaharan"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
