#baseurl = "http://replace-this-with-your-hugo-site.com/"
#languageCode = "en-us"
#title = "My New Hugo Site"
baseurl = "http://tsukaharan.github.io/"
languageCode = "ja"
title = "tsukaharan blog"
canonifyurls = true
theme = "beautifulhugo"
